export { default as FzLayout } from './FzLayout.vue'
export { default as FzLayoutMain } from './FzLayoutMain.vue'
export { default as FzLayoutHeader } from './FzLayoutHeader.vue'
export { default as FzLayoutAside } from './FzLayoutAside.vue'
export { default as FzLayoutFooter } from './FzLayoutFooter.vue'
export { default as FzLayoutBottomBar } from './FzLayoutBottomBar.vue'
export { default as FzBlankTemplate } from './FzBlankTemplate.vue'
export { default as FzFocusTemplate } from './FzFocusTemplate.vue'
export { default as FzAppTemplate } from './FzAppTemplate.vue'
export { default as FzListTemplate } from './FzListTemplate.vue'
export { default as FzDetailTemplate } from './FzDetailTemplate.vue'
export { FZ_BOTTOM_BAR_TARGET } from './keys'
export type * from './types'
