#!/bin/sh

echo "🧪 Running affected tests..."
npx nx affected -t test:unit
TEST_EXIT=$?
if [ $TEST_EXIT -ne 0 ]; then
  exit $TEST_EXIT
fi

echo "🔨 Building affected packages..."
npx nx affected -t build
exit $?

